-- AlterTable
ALTER TABLE `File` ADD COLUMN `filmId` VARCHAR(191) NULL;

-- AddForeignKey
ALTER TABLE `File` ADD CONSTRAINT `File_filmId_fkey` FOREIGN KEY (`filmId`) REFERENCES `Film`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
